### ISSUE TITLE
Why does this not working with > iOS 15

### ISSUE THREAD

**Issue by tapthaker** [david8lumen/MemoryGraph#1]
Just wondering, I'd like to put in some effort to get it working if its possible.

**Comment by david8lumen** [comment]
Hi @tapthaker thank you for reaching out!

It seems that Apple has fixed and patched some functions so now it is not possible to retrieve a necessary information from memory starting from iOS 15.

I also noticed that if you try to launch this tool on iOS 15 device, the system will try to send this action directly to Apple with the relative information. I made this assumption based on the information that I am getting in Xcode's lldb log while launching this tool :)

**Comment by tapthaker** [comment]
Thanks for the context. 👍. I’ll close this issue now.
